name: Gradle publish services shared lib

on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    name: core-shared-build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup java project env
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Publish with Gradle
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}