name: Gradle publish

on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    name: publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup java project env
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setup Android SDK Tools
        uses: android-actions/setup-android@v2.0.2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Publish with gradle
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}